// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PMStudio.Models;

namespace PMStudio.Migrations
{
    [DbContext(typeof(PMStudioContext))]
    [Migration("20190829170737_RelationshipIdentityEntity")]
    partial class RelationshipIdentityEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("C##PMSTUDIO")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73724", "'ISEQ$$_73724', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73727", "'ISEQ$$_73727', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73730", "'ISEQ$$_73730', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73733", "'ISEQ$$_73733', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73736", "'ISEQ$$_73736', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73739", "'ISEQ$$_73739', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73746", "'ISEQ$$_73746', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73749", "'ISEQ$$_73749', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73752", "'ISEQ$$_73752', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73755", "'ISEQ$$_73755', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.ISEQ$$_73758", "'ISEQ$$_73758', '', '1', '1', '', '', 'Int64', 'False'");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PMStudio.Areas.Identity.Data.PMStudioUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.Acciones", b =>
                {
                    b.Property<decimal>("IdAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_ACCION")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(30)");

                    b.HasKey("IdAccion")
                        .HasName("ACCIONES_PK");

                    b.HasIndex("IdAccion")
                        .IsUnique()
                        .HasName("ACCIONES_PK");

                    b.ToTable("ACCIONES");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.InstanciasPlantillas", b =>
                {
                    b.Property<decimal>("IdInstanciaPlantilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_INSTANCIA_PLANTILLA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("AspNetUser")
                        .IsRequired()
                        .HasColumnName("ASPNETUSER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnName("ESTADO")
                        .HasColumnType("CHAR(1)");

                    b.Property<string>("Iniciada")
                        .IsRequired()
                        .HasColumnName("INICIADA")
                        .HasColumnType("CHAR(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<decimal>("Usuario")
                        .HasColumnName("USUARIO")
                        .HasColumnType("NUMBER(38)");

                    b.HasKey("IdInstanciaPlantilla")
                        .HasName("INSTANCIAS_PLANTILLAS_PK");

                    b.HasIndex("AspNetUser");

                    b.HasIndex("IdInstanciaPlantilla")
                        .IsUnique()
                        .HasName("INSTANCIAS_PLANTILLAS_PK");

                    b.HasIndex("Usuario");

                    b.ToTable("INSTANCIAS_PLANTILLAS");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.InstanciasPlantillasDatosDetalle", b =>
                {
                    b.Property<decimal>("IdInstanciaPlantillaDato")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_INSTANCIA_PLANTILLA_DATO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Dato")
                        .IsRequired()
                        .HasColumnName("DATO")
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<decimal>("Instanciaplantilla")
                        .HasColumnName("INSTANCIAPLANTILLA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasColumnName("NOMBRE_CAMPO")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("IdInstanciaPlantillaDato")
                        .HasName("INSTANCIAS_PLANTILLAS_DATOS_DETALLE_PK");

                    b.HasIndex("IdInstanciaPlantillaDato")
                        .IsUnique()
                        .HasName("INSTANCIAS_PLANTILLAS_DATOS_DETALLE_PK");

                    b.HasIndex("Instanciaplantilla");

                    b.ToTable("INSTANCIAS_PLANTILLAS_DATOS_DETALLE");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.InstanciasPlantillasPasosDetalle", b =>
                {
                    b.Property<decimal>("IdPlantillaPasoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PLANTILLA_PASO_DETALLE")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("AspNetUser")
                        .HasColumnName("ASPNETUSER");

                    b.Property<decimal?>("Estado")
                        .HasColumnName("ESTADO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("InstanciaPlantilla")
                        .HasColumnName("INSTANCIA_PLANTILLA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Paso")
                        .HasColumnName("PASO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal?>("UsuarioAccion")
                        .HasColumnName("USUARIO_ACCION")
                        .HasColumnType("NUMBER(38)");

                    b.HasKey("IdPlantillaPasoDetalle")
                        .HasName("INSTANCIAS_PLANTILLAS_PASOS_DETALLE_PK");

                    b.HasIndex("AspNetUser");

                    b.HasIndex("Estado");

                    b.HasIndex("IdPlantillaPasoDetalle")
                        .IsUnique()
                        .HasName("INSTANCIAS_PLANTILLAS_PASOS_DETALLE_PK");

                    b.HasIndex("InstanciaPlantilla");

                    b.HasIndex("Paso");

                    b.HasIndex("UsuarioAccion");

                    b.ToTable("INSTANCIAS_PLANTILLAS_PASOS_DETALLE");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.Pasos", b =>
                {
                    b.Property<decimal>("IdPaso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PASO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("IdPaso")
                        .HasName("PASOS_PK");

                    b.HasIndex("IdPaso")
                        .IsUnique()
                        .HasName("PASOS_PK");

                    b.ToTable("PASOS");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PasosInstancias", b =>
                {
                    b.Property<decimal>("IdPasoinstancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PASOINSTANCIA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("IdPasoinstancia")
                        .HasName("PASOS_INSTANCIAS_PK");

                    b.HasIndex("IdPasoinstancia")
                        .IsUnique()
                        .HasName("PASOS_INSTANCIAS_PK");

                    b.ToTable("PASOS_INSTANCIAS");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PasosInstanciasDatosDetalle", b =>
                {
                    b.Property<decimal>("IdPasosInstanciasDatos")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PASOS_INSTANCIAS_DATOS")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("InstanciaPlantillaDato")
                        .HasColumnName("INSTANCIA_PLANTILLA_DATO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Paso")
                        .HasColumnName("PASO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("SoloLectura")
                        .IsRequired()
                        .HasColumnName("SOLO_LECTURA")
                        .HasColumnType("CHAR(1)");

                    b.HasKey("IdPasosInstanciasDatos")
                        .HasName("PASOS_INSTANCIAS_DATOS_DETALLE_PK");

                    b.HasIndex("IdPasosInstanciasDatos")
                        .IsUnique()
                        .HasName("PASOS_INSTANCIAS_DATOS_DETALLE_PK");

                    b.HasIndex("InstanciaPlantillaDato");

                    b.HasIndex("Paso");

                    b.ToTable("PASOS_INSTANCIAS_DATOS_DETALLE");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PasosUsuariosDetalle", b =>
                {
                    b.Property<decimal>("IdPasosUsuarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PASOS_USUARIOS")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("AspNetUser")
                        .IsRequired()
                        .HasColumnName("ASPNETUSER");

                    b.Property<decimal>("PlantillaPasoDetalle")
                        .HasColumnName("PLANTILLA_PASO_DETALLE")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Usuario")
                        .HasColumnName("USUARIO")
                        .HasColumnType("NUMBER(38)");

                    b.HasKey("IdPasosUsuarios")
                        .HasName("PASOS_USUARIOS_DETALLE_PK");

                    b.HasIndex("AspNetUser");

                    b.HasIndex("IdPasosUsuarios")
                        .IsUnique()
                        .HasName("PASOS_USUARIOS_DETALLE_PK");

                    b.HasIndex("PlantillaPasoDetalle");

                    b.HasIndex("Usuario");

                    b.ToTable("PASOS_USUARIOS_DETALLE");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.Plantillas", b =>
                {
                    b.Property<decimal>("IdPlantilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_PLANTILLA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("VARCHAR2(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("IdPlantilla")
                        .HasName("PLANTILLAS_PK");

                    b.HasIndex("IdPlantilla")
                        .IsUnique()
                        .HasName("PLANTILLAS_PK");

                    b.ToTable("PLANTILLAS");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PlantillasCamposDetalle", b =>
                {
                    b.Property<decimal>("IdPlantillaCampo")
                        .HasColumnName("ID_PLANTILLA_CAMPO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Plantilla")
                        .HasColumnName("PLANTILLA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("NombreCampo")
                        .IsRequired()
                        .HasColumnName("NOMBRE_CAMPO")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("IdPlantillaCampo", "Plantilla")
                        .HasName("PLANTILLAS_CAMPOS_DETALLE_PK");

                    b.HasIndex("Plantilla");

                    b.HasIndex("IdPlantillaCampo", "Plantilla")
                        .IsUnique()
                        .HasName("PLANTILLAS_CAMPOS_DETALLE_PK");

                    b.ToTable("PLANTILLAS_CAMPOS_DETALLE");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PlantillasPasosDetalle", b =>
                {
                    b.Property<decimal>("IdPlantillaPaso")
                        .HasColumnName("ID_PLANTILLA_PASO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Plantilla")
                        .HasColumnName("PLANTILLA")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Paso")
                        .HasColumnName("PASO")
                        .HasColumnType("NUMBER(38)");

                    b.HasKey("IdPlantillaPaso", "Plantilla")
                        .HasName("PLANTILLAS_PASOS_DETALLE_PK");

                    b.HasIndex("Paso");

                    b.HasIndex("Plantilla");

                    b.HasIndex("IdPlantillaPaso", "Plantilla")
                        .IsUnique()
                        .HasName("PLANTILLAS_PASOS_DETALLE_PK");

                    b.ToTable("PLANTILLAS_PASOS_DETALLE");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.Rangos", b =>
                {
                    b.Property<decimal>("IdRango")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_RANGO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<decimal>("Nivel")
                        .HasColumnName("NIVEL")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NOMBRE")
                        .HasColumnType("VARCHAR2(50)");

                    b.HasKey("IdRango")
                        .HasName("RANGOS_PK");

                    b.HasIndex("IdRango")
                        .IsUnique()
                        .HasName("RANGOS_PK");

                    b.ToTable("RANGOS");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.Usuarios", b =>
                {
                    b.Property<decimal>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_USUARIO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnName("APELLIDOS")
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnName("NOMBRES")
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<decimal>("Rango")
                        .HasColumnName("RANGO")
                        .HasColumnType("NUMBER(38)");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnName("USUARIO_EMAIL")
                        .HasColumnType("VARCHAR2(30)");

                    b.HasKey("IdUsuario")
                        .HasName("USUARIOS_PK");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasName("USUARIOS_PK");

                    b.HasIndex("Rango");

                    b.ToTable("USUARIOS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PMStudio.Models.Entities.InstanciasPlantillas", b =>
                {
                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser", "AspNetUserNavigation")
                        .WithMany("InstanciasPlantillas")
                        .HasForeignKey("AspNetUser");

                    b.HasOne("PMStudio.Models.Entities.Usuarios", "UsuarioNavigation")
                        .WithMany("InstanciasPlantillas")
                        .HasForeignKey("Usuario")
                        .HasConstraintName("INSTANCIAS_PLANTILLAS_FK1");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.InstanciasPlantillasDatosDetalle", b =>
                {
                    b.HasOne("PMStudio.Models.Entities.InstanciasPlantillas", "InstanciaplantillaNavigation")
                        .WithMany("InstanciasPlantillasDatosDetalle")
                        .HasForeignKey("Instanciaplantilla")
                        .HasConstraintName("INSTANCIAS_PLANTILLAS_DATOS_DETALLE_FK1")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PMStudio.Models.Entities.InstanciasPlantillasPasosDetalle", b =>
                {
                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser", "AspNetUserNavigation")
                        .WithMany("InstanciasPlantillasPasosDetalle")
                        .HasForeignKey("AspNetUser");

                    b.HasOne("PMStudio.Models.Entities.Acciones", "EstadoNavigation")
                        .WithMany("InstanciasPlantillasPasosDetalle")
                        .HasForeignKey("Estado")
                        .HasConstraintName("INSTANCIAS_PLANTILLAS_PASOS_DETALLE_FK2");

                    b.HasOne("PMStudio.Models.Entities.InstanciasPlantillas", "InstanciaPlantillaNavigation")
                        .WithMany("InstanciasPlantillasPasosDetalle")
                        .HasForeignKey("InstanciaPlantilla")
                        .HasConstraintName("INSTANCIAS_PLANTILLAS_PASOS_DETALLE_FK3")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMStudio.Models.Entities.PasosInstancias", "PasoNavigation")
                        .WithMany("InstanciasPlantillasPasosDetalle")
                        .HasForeignKey("Paso")
                        .HasConstraintName("INSTANCIAS_PLANTILLAS_PASOS_DETALLE_FK1");

                    b.HasOne("PMStudio.Models.Entities.Usuarios", "UsuarioAccionNavigation")
                        .WithMany("InstanciasPlantillasPasosDetalle")
                        .HasForeignKey("UsuarioAccion")
                        .HasConstraintName("INSTANCIAS_PLANTILLAS_PASOS_DETALLE_FK4");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PasosInstanciasDatosDetalle", b =>
                {
                    b.HasOne("PMStudio.Models.Entities.InstanciasPlantillasDatosDetalle", "InstanciaPlantillaDatoNavigation")
                        .WithMany("PasosInstanciasDatosDetalle")
                        .HasForeignKey("InstanciaPlantillaDato")
                        .HasConstraintName("PASOS_INSTANCIAS_DATOS_DETALLE_FK1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMStudio.Models.Entities.PasosInstancias", "PasoNavigation")
                        .WithMany("PasosInstanciasDatosDetalle")
                        .HasForeignKey("Paso")
                        .HasConstraintName("PASOS_INSTANCIAS_DATOS_DETALLE_FK2");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PasosUsuariosDetalle", b =>
                {
                    b.HasOne("PMStudio.Areas.Identity.Data.PMStudioUser", "AspNetUserNavigation")
                        .WithMany("PasosUsuariosDetalle")
                        .HasForeignKey("AspNetUser");

                    b.HasOne("PMStudio.Models.Entities.InstanciasPlantillasPasosDetalle", "PlantillaPasoDetalleNavigation")
                        .WithMany("PasosUsuariosDetalle")
                        .HasForeignKey("PlantillaPasoDetalle")
                        .HasConstraintName("PASOS_USUARIOS_DETALLE_FK1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMStudio.Models.Entities.Usuarios", "UsuarioNavigation")
                        .WithMany("PasosUsuariosDetalle")
                        .HasForeignKey("Usuario")
                        .HasConstraintName("PASOS_USUARIOS_DETALLE_FK2");
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PlantillasCamposDetalle", b =>
                {
                    b.HasOne("PMStudio.Models.Entities.Plantillas", "PlantillaNavigation")
                        .WithMany("PlantillasCamposDetalle")
                        .HasForeignKey("Plantilla")
                        .HasConstraintName("PLANTILLAS_CAMPOS_DETALLE_FK1")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PMStudio.Models.Entities.PlantillasPasosDetalle", b =>
                {
                    b.HasOne("PMStudio.Models.Entities.Pasos", "PasoNavigation")
                        .WithMany("PlantillasPasosDetalle")
                        .HasForeignKey("Paso")
                        .HasConstraintName("PLANTILLAS_PASOS_DETALLE_FK2");

                    b.HasOne("PMStudio.Models.Entities.Plantillas", "PlantillaNavigation")
                        .WithMany("PlantillasPasosDetalle")
                        .HasForeignKey("Plantilla")
                        .HasConstraintName("PLANTILLAS_PASOS_DETALLE_FK1")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PMStudio.Models.Entities.Usuarios", b =>
                {
                    b.HasOne("PMStudio.Models.Entities.Rangos", "RangoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("Rango")
                        .HasConstraintName("USUARIOS_FK1");
                });
#pragma warning restore 612, 618
        }
    }
}
